version: '3'

services:
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          target: /dc-bot
          path: ./discord-bot
    env_file: ./.env

  nettskjema-parser:
    build:
      context: ./nettskjema-parser
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          target: /parser
          path: ./nettskjema-parser
    env_file: ./.env